### ISSUE TITLE
请问我把它放在企业微信应用里面的接收消息也可以吧？

### ISSUE THREAD

**Issue by CapitaineNemo** [easy-wx/wecom-bot-svr#1]
感谢分享，我用在这里应该也可以吧？
![image](https://github.com/panzhongxian/wecom-bot-svr/assets/25415402/a1fb2577-c452-44e9-8b7b-d005f0c4b2e7)

**Comment by panzhongxian** [comment]
@CapitaineNemo 我看你应是说的微信客服账号对吧？我看API好像有些类似，但是没有实际使用。
你可以试试，然后反馈一下有什么问题哈。


看上去机器人接收消息的协议和其他接收消息的协议是不同的，我们可以做一个兼容。让一个框架，来匹配两个种协议，用户可以在创建基础的Server的时候自行选择，而无需用户了解，只需要进行消息处理即可。

机器人协议：https://developer.work.weixin.qq.com/document/path/95280

客服接收消息协议：https://developer.work.weixin.qq.com/document/path/94670
公众号接收消息协议：https://developers.weixin.qq.com/doc/offiaccount/Getting_Started/Getting_Started_Guide.html

**Comment by panzhongxian** [comment]
@CapitaineNemo https://developer.work.weixin.qq.com/document/path/90238
我刚才试了一下，可以创建“应用”，也可以实现接收消息和回复消息的功能。但是无法被邀请到群中

但是他的协议跟机器人的不同，我打算另外开一个仓库，来适配企业微信应用的回复消息。
另外的一点不同是，应用这里需要填上企业的ID

**Comment by timiil** [comment]
> @CapitaineNemo https://developer.work.weixin.qq.com/document/path/90238 我刚才试了一下，可以创建“应用”，也可以实现接收消息和回复消息的功能。但是无法被邀请到群中
> 
> 但是他的协议跟机器人的不同，我打算另外开一个仓库，来适配企业微信应用的回复消息。 另外的一点不同是，应用这里需要填上企业的ID

你好，我们也希望在“应用”内收听用户上行的请求消息然后做处理并响应， 这个场景跟机器人进群有点不同。 请问目前项目是否支持这种消息订阅?

**Comment by panzhongxian** [comment]
@timiil 我这两天新创建个项目处理应用的，然后给个实例说明

**Comment by panzhongxian** [comment]
@timiil @CapitaineNemo  我这里搞了一个新项目，用来创建应用的回调，可以试试：
https://github.com/easy-wx/wecom-app-svr
