### ISSUE TITLE
新建的机器人怎么没有接收消息配置啊

### ISSUE THREAD

**Issue by liangweidonggood** [easy-wx/wecom-bot-svr#3]

**Comment by liangweidonggood** [comment]
![image](https://github.com/easy-wx/wecom-bot-svr/assets/6304507/9851b368-0bdc-4f80-a1d2-ae9e852fd6f9)

**Comment by panzhongxian** [comment]
https://github.com/panzhongxian/blog-comments/issues/4#issuecomment-2034008979

这里有人提到，“刚问了企微助手，说是这个功能暂时只有腾讯内部开放了😂”。
可能确实是功能还没有完全开放。

**Comment by EverSpring** [comment]
我的也没有，有什么办法可以申请开放吗？
